### ISSUE TITLE
有兼容Android10 ？

### ISSUE THREAD

**Issue by callhh** [BeaHugs/RxImagePicker#3]
如
1.拍照和选择照片时的加载显示问题
2.选择后的回显问题?

**Comment by BeaHugs** [comment]
可以的,  有问题可以联系我

**Comment by callhh** [comment]
> 可以的, 有问题可以联系我

测试机，华为P30，安卓系统10
1，打开相册后，前面几张图正常显示并且可预览。后面的图就全部是黑色，并且不可预览！
2，建议多增加一个，也可以选择视频文件，同时用户选择的时候只能选择一种，也就是图片或视频，二选一

**Comment by BeaHugs** [comment]
感谢你的关注,   后期我将会添加这些功能

**Comment by BeaHugs** [comment]
您的第一个问题在  meat 30 pro  Android 10  没有发现类似的问题 ,   你能不能提供一下日志,   
第二个问题,近期我将会添加
