### ISSUE TITLE
裁剪的图片的上下有黑边

### ISSUE THREAD

**Issue by PPeanutButter** [BeaHugs/RxImagePicker#4]
裁剪比例小的话没有，1.6开始就有了，

**Comment by BeaHugs** [comment]
你是在哪一款手机上遇到的问题,

**Comment by PPeanutButter** [comment]
小米4的原生android10设备和api29的android studio模拟器都有
第一张小米4，
[cid:image001.jpg@01D5E71B.74AAEDF0]
第二张avd截图

[cid:image002.png@01D5E71B.823AC300]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: BeaHugs<mailto:notifications@github.com>
发送时间: 2020年2月19日 11:53
收件人: BeaHugs/RxImagePicker<mailto:RxImagePicker@noreply.github.com>
抄送: PPeanutButter<mailto:panrunqiu@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [BeaHugs/RxImagePicker] 裁剪的图片的上下有黑边 (#4)


你是在哪一款手机上遇到的问题,

―

**Comment by PPeanutButter** [comment]
啥时候能抽时间修一下啊😂

**Comment by BeaHugs** [comment]
好的，周六周日修改一下  谢谢你的反馈


| |
王毅博
|
|
邮箱：13522932731@163.com
|

签名由 网易邮箱大师 定制

在2020年02月20日 11:12，PPeanutButter 写道：

啥时候能抽时间修一下啊😂

**Comment by PPeanutButter** [comment]
大佬，'com.github.pqpo:SmartCropper:v2.1.3'这个包打包出来有50多MB的.so

**Comment by BeaHugs** [comment]
剪裁想换成框架，但是发现这个有问题准备换另一个，   现在还没有改好




| |
王毅博
|
|
邮箱：13522932731@163.com
|

签名由 网易邮箱大师 定制

在2020年03月02日 15:32，PPeanutButter 写道：

大佬，'com.github.pqpo:SmartCropper:v2.1.3'这个包打包出来有50多MB的.so

**Comment by PPeanutButter** [comment]
好，那我回滚

**Comment by BeaHugs** [comment]
如果你有好的想法，也可以和我说，   因为现在工作比较忙，维护的速度比较慢




| |
王毅博
|
|
邮箱：13522932731@163.com
|

签名由 网易邮箱大师 定制

在2020年03月02日 15:37，PPeanutButter 写道：

好，那我回滚

**Comment by PPeanutButter** [comment]
我也准备考研复试毕业设计没多少时间，裁剪库我找一个试试，好用再告诉你

**Comment by PPeanutButter** [comment]
我没有找到体积小好用的裁剪库，于是我动手修改了你的库，发现不能裁剪全屏大小比例的问题就是你的process_img本身就没有全屏显示，于是我换了linearlauout为ConstraintLayout，让rl_top_bar半透明（我不知道imageview部分被遮挡的话系统会不会不绘制）然后全屏显示这个ImageClipActivity就可以裁剪全屏比例的图片了（当然再大比例的图片上下还是会有黑边，但我的app只需要屏幕大小比例，大部分都只要这个比例吧）

**Comment by PPeanutButter** [comment]
process_img也可以通过
android:layout_marginStart="30dp"
android:layout_marginEnd="30dp"
来增加到比屏幕比例还大的比例

**Comment by PPeanutButter** [comment]
https://imgchr.com/i/3fIx3j
https://imgchr.com/i/3fI7ut
修改前后的手机截图

**Comment by BeaHugs** [comment]
1257924355    加我QQ   私聊吧，    方便一些




| |
王毅博
|
|
邮箱：13522932731@163.com
|

签名由 网易邮箱大师 定制

在2020年03月03日 10:08，PPeanutButter 写道：

https://imgchr.com/i/3fIx3j
https://imgchr.com/i/3fI7ut
修改前后的手机截图
