### ISSUE TITLE
请问支持 全选/反选 整个本地相册吗？

### ISSUE THREAD

**Issue by DMingOu** [BeaHugs/RxImagePicker#5]
RT，请问支持 全选/反选 整个本地相册吗？如何设置

需求是点击全选/反选整个相册，不是点击进行多选。

**Comment by BeaHugs** [comment]
暂时不支持点击全选/反选整个相册

**Comment by DMingOu** [comment]
@BeaHugs 
有比较好的方法处理这个项目需求吗，我找到的其他开源库也不支持全选/反选 整个本地相册。

**Comment by BeaHugs** [comment]
可以实现
